version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./test:/app/test
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
    command: npm start
  
  frontend:
    build:
      context: ./public/dashboard-app
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./public/dashboard-app/src:/app/src
      - ./public/dashboard-app/public:/app/public
    environment:
      - PORT=3001
    depends_on:
      - app