PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
INSERT INTO SequelizeMeta VALUES('20250924000000-create-users.js');
CREATE TABLE `Users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `username` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `role` VARCHAR(255) DEFAULT 'user', `is_verified` TINYINT(1) DEFAULT 0, `verification_token` VARCHAR(255), `reset_token` VARCHAR(255), `reset_token_expires_at` DATETIME, `remember_token` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
INSERT INTO Users VALUES(1,'administrator','admin@example.com','$2b$10$9jpFd4P.M7.0KSsaQ0y7iur/GZt4CI6QlMXsGLYvuoCRbiJIsAMlG','admin',1,NULL,NULL,NULL,NULL,'2025-12-13 18:54:06.065 +00:00','2025-12-13 18:54:06.065 +00:00');
CREATE TABLE `activity_logs` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `userId` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `action` VARCHAR(255) NOT NULL, `description` TEXT, `ipAddress` VARCHAR(255), `userAgent` TEXT, `metadata` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `notifications` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `userId` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `type` VARCHAR(255) NOT NULL DEFAULT 'info', `title` VARCHAR(255) NOT NULL, `message` TEXT NOT NULL, `isRead` TINYINT(1) DEFAULT 0, `readAt` DATETIME, `link` VARCHAR(255), `metadata` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `notes` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `userId` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `title` VARCHAR(255) NOT NULL, `content` TEXT, `color` VARCHAR(255) DEFAULT 'default', `isPinned` TINYINT(1) DEFAULT 0, `tags` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `user_settings` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `userId` INTEGER NOT NULL UNIQUE REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `theme` VARCHAR(255) DEFAULT 'light', `language` VARCHAR(255) DEFAULT 'en', `timezone` VARCHAR(255) DEFAULT 'UTC', `emailNotifications` TINYINT(1) DEFAULT 1, `securityAlerts` TINYINT(1) DEFAULT 1, `marketingEmails` TINYINT(1) DEFAULT 0, `twoFactorEnabled` TINYINT(1) DEFAULT 0, `preferences` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `Tenders` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `title` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `reference_number` VARCHAR(255) NOT NULL UNIQUE, `organization` VARCHAR(255) NOT NULL, `category` TEXT NOT NULL DEFAULT 'Other', `location` VARCHAR(255) NOT NULL, `estimated_value` DECIMAL(15,2), `currency` VARCHAR(3) NOT NULL DEFAULT 'USD', `submission_deadline` DATETIME NOT NULL, `published_date` DATETIME NOT NULL, `status` TEXT NOT NULL DEFAULT 'Active', `contact_person` VARCHAR(255), `contact_email` VARCHAR(255), `contact_phone` VARCHAR(255), `requirements` TEXT, `documents_required` JSON DEFAULT '[]', `eligibility_criteria` TEXT, `evaluation_criteria` TEXT, `tags` JSON DEFAULT '[]', `is_featured` TINYINT(1) NOT NULL DEFAULT 0, `view_count` INTEGER NOT NULL DEFAULT 0, `created_by` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `TenderApplications` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `tender_id` INTEGER NOT NULL REFERENCES `Tenders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `applicant_id` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, `company_name` VARCHAR(255) NOT NULL, `company_registration` VARCHAR(255), `contact_person` VARCHAR(255) NOT NULL, `contact_email` VARCHAR(255) NOT NULL, `contact_phone` VARCHAR(255), `proposal_summary` TEXT NOT NULL, `quoted_amount` DECIMAL(15,2) NOT NULL, `currency` VARCHAR(3) NOT NULL DEFAULT 'USD', `delivery_timeline` VARCHAR(255), `experience_years` INTEGER, `previous_projects` JSON DEFAULT '[]', `certifications` JSON DEFAULT '[]', `status` TEXT NOT NULL DEFAULT 'Submitted', `submitted_at` DATETIME NOT NULL, `reviewed_at` DATETIME, `reviewer_notes` TEXT, `score` DECIMAL(3,2), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `TenderDocuments` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `tender_id` INTEGER NOT NULL REFERENCES `Tenders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `name` VARCHAR(255) NOT NULL, `description` TEXT, `file_path` VARCHAR(255) NOT NULL, `file_size` INTEGER NOT NULL, `file_type` VARCHAR(255) NOT NULL, `category` TEXT NOT NULL DEFAULT 'Tender Document', `is_required` TINYINT(1) NOT NULL DEFAULT 0, `download_count` INTEGER NOT NULL DEFAULT 0, `uploaded_by` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
CREATE TABLE `ApplicationDocuments` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `application_id` INTEGER NOT NULL REFERENCES `TenderApplications` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `name` VARCHAR(255) NOT NULL, `description` TEXT, `file_path` VARCHAR(255) NOT NULL, `file_size` INTEGER NOT NULL, `file_type` VARCHAR(255) NOT NULL, `category` TEXT NOT NULL DEFAULT 'Other', `uploaded_by` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Users',1);
CREATE INDEX `activity_logs_user_id` ON `activity_logs` (`userId`);
CREATE INDEX `activity_logs_action` ON `activity_logs` (`action`);
CREATE INDEX `activity_logs_created_at` ON `activity_logs` (`createdAt`);
CREATE INDEX `notifications_user_id` ON `notifications` (`userId`);
CREATE INDEX `notifications_is_read` ON `notifications` (`isRead`);
CREATE INDEX `notifications_created_at` ON `notifications` (`createdAt`);
CREATE INDEX `notes_user_id` ON `notes` (`userId`);
CREATE INDEX `notes_is_pinned` ON `notes` (`isPinned`);
CREATE INDEX `notes_created_at` ON `notes` (`createdAt`);
CREATE INDEX `user_settings_user_id` ON `user_settings` (`userId`);
CREATE INDEX `tenders_category` ON `Tenders` (`category`);
CREATE INDEX `tenders_location` ON `Tenders` (`location`);
CREATE INDEX `tenders_status` ON `Tenders` (`status`);
CREATE INDEX `tenders_submission_deadline` ON `Tenders` (`submission_deadline`);
CREATE INDEX `tenders_published_date` ON `Tenders` (`published_date`);
CREATE UNIQUE INDEX `tenders_reference_number` ON `Tenders` (`reference_number`);
CREATE INDEX `tender_applications_tender_id` ON `TenderApplications` (`tender_id`);
CREATE INDEX `tender_applications_applicant_id` ON `TenderApplications` (`applicant_id`);
CREATE INDEX `tender_applications_status` ON `TenderApplications` (`status`);
CREATE INDEX `tender_applications_submitted_at` ON `TenderApplications` (`submitted_at`);
CREATE UNIQUE INDEX `tender_applications_tender_id_applicant_id` ON `TenderApplications` (`tender_id`, `applicant_id`);
CREATE INDEX `tender_documents_tender_id` ON `TenderDocuments` (`tender_id`);
CREATE INDEX `tender_documents_category` ON `TenderDocuments` (`category`);
CREATE INDEX `tender_documents_file_type` ON `TenderDocuments` (`file_type`);
CREATE INDEX `tender_documents_uploaded_by` ON `TenderDocuments` (`uploaded_by`);
CREATE INDEX `application_documents_application_id` ON `ApplicationDocuments` (`application_id`);
CREATE INDEX `application_documents_category` ON `ApplicationDocuments` (`category`);
CREATE INDEX `application_documents_file_type` ON `ApplicationDocuments` (`file_type`);
CREATE INDEX `application_documents_uploaded_by` ON `ApplicationDocuments` (`uploaded_by`);
COMMIT;
