name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup ZAP configuration
        run: |
          sudo mkdir -p /zap/wrk
          sudo chmod 777 /zap/wrk
          # Copy the ZAP configuration to the working directory
          sudo cp .zap/zap.yaml /zap/wrk/zap.yaml
          sudo chmod 666 /zap/wrk/zap.yaml

      - name: Run npm audit
        run: npm run test:security

      - name: Start application
        run: |
          npm run start:ci &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV
          # Wait for application to be ready
          for i in {1..30}; do
            if curl -f http://localhost:3000/api/health &>/dev/null; then
              echo "Application is ready"
              break
            fi
            echo "Waiting for application to start... ($i/30)"
            sleep 5
          done
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret

      - name: Run OWASP ZAP Automation Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -autorun /zap/wrk/zap.yaml'
          allow_issue_writing: false
          fail_action: false

      - name: Stop application
        if: always()
        run: |
          if [ ! -z "$APP_PID" ]; then
            kill $APP_PID || true
          fi
          pkill -f "node.*server.js" || true

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            /zap/wrk/zap-report.html
            /zap/wrk/report.*
            /tmp/zap_report*