name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm run test:security

      - name: Start application
        run: |
          npm run start:ci &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV
          # Wait for application to be ready
          for i in {1..30}; do
            if curl -f http://localhost:3000/api/health &>/dev/null; then
              echo "Application is ready"
              break
            fi
            echo "Waiting for application to start... ($i/30)"
            sleep 5
          done
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -m 3 -T 15'
          allow_issue_writing: false
          fail_action: false
          artifact_name: 'security-scan-report'

      - name: Stop application
        if: always()
        run: |
          if [ ! -z "$APP_PID" ]; then
            kill $APP_PID || true
          fi
          pkill -f "node.*server.js" || true

      - name: List generated reports
        if: always()
        run: |
          echo "=== Checking for ZAP report files ==="
          ls -la report_* || echo "No report files found with report_* pattern"
          ls -la *.html *.json *.md || echo "No report files found with extensions"
          find . -name "*report*" -type f || echo "No files with 'report' in name found"
          echo "=== Current directory contents ==="
          ls -la

      - name: Upload ZAP Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: |
            report_json.json
            report_md.md
            report_html.html
          retention-days: 7
          if-no-files-found: warn