name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run backend tests
      run: npm run test:backend
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test-jwt-secret' }}
        NODE_ENV: test
    
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'public/dashboard-app/package-lock.json'
    
    - name: Install frontend dependencies
      run: |
        cd public/dashboard-app
        npm ci
    
    - name: Run frontend tests with coverage
      run: |
        cd public/dashboard-app
        npm run test:ci
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: public/dashboard-app/coverage/
  
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install wait-on for server coordination
      run: npm install -g wait-on
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Start backend server
      run: |
        npm run start:ci &
        echo $! > backend.pid
      env:
        JWT_SECRET: test-jwt-secret
        NODE_ENV: test
    
    - name: Install frontend dependencies and start server
      run: |
        cd public/dashboard-app
        npm ci
        npm start &
        echo $! > ../../frontend.pid
    
    - name: Wait for servers to start
      run: |
        npx wait-on http://localhost:3000/api/health --timeout 60000
        npx wait-on http://localhost:3001 --timeout 60000
    
    - name: Run Playwright tests
      run: npm run playwright:test
      env:
        JWT_SECRET: test-jwt-secret
        NODE_ENV: test
    
    - name: Stop servers
      if: always()
      run: |
        if [ -f backend.pid ]; then kill $(cat backend.pid) || true; fi
        if [ -f frontend.pid ]; then kill $(cat frontend.pid) || true; fi
    
    - name: Archive test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: |
          playwright-report/
          test-results/